---
name: mfa-authenticator
After:
  - #coresecurity
---
Injector:
  Security:
    properties:
      Authenticators:
        default: %$SilverStripe\MFA\Authenticator\MemberAuthenticator
---
name: mfa-memberextension
---
Member:
  extensions:
    mfaExtension: SilverStripe\MFA\Extension\MemberExtension
    accountResetExtension: SilverStripe\MFA\Extension\AccountReset\MemberExtension
Security:
  extensions:
    accountResetExtension: SilverStripe\MFA\Extension\AccountReset\SecurityExtension
SilverStripe\MFA\Extension\AccountReset\SecurityExtension:
  extensions:
    mfaResetExtension: SilverStripe\MFA\Extension\AccountReset\MFAResetExtension
