---
name: mfa-authenticator
---
Authenticator:
  authenticators:
    - SilverStripe\MFA\Authenticator\MemberAuthenticator
  default_authenticator: SilverStripe\MFA\Authenticator\MemberAuthenticator
---
name: mfa-memberextension
---
Member:
  extensions:
    mfaExtension: SilverStripe\MFA\Extension\MemberExtension
    accountResetExtension: SilverStripe\MFA\Extension\AccountReset\MemberExtension
Security:
  extensions:
    accountResetExtension: SilverStripe\MFA\Extension\AccountReset\SecurityExtension
    changePasswordExtension: SilverStripe\MFA\Extension\ChangePasswordExtension
